WebShop-Candy/Controllers/CandyController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop_Candy.Models;
using WebShop_Candy.Service;
using WebShop_Candy.ViewModels;

namespace WebShop_Candy.Controllers
{
    public class CandyController : Controller
    {

        private readonly ICandyRepository _candyRepository;
        private readonly ICategoryRepository _categoryRepository;

        public CandyController(ICandyRepository candyRepository,ICategoryRepository categoryRepository)
        {
            _candyRepository = candyRepository;
            _categoryRepository = categoryRepository;
        }




        public IActionResult List(string category)
        {
            IEnumerable<Candy> candies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                candies = _candyRepository.GetAllCandy.OrderBy(c => c.CandyId);
                currentCategory = "All Candy";
            }
            else
            {
                candies = _candyRepository.GetAllCandy.
                    Where(c => c.Category.CategoryName == category);

                currentCategory = _categoryRepository.GetAllCategories.
                    FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }
            return View(new CandyListViewModel
            {
                Candies = candies,
                CurrentCategory = currentCategory,
            });
           
        }

        public IActionResult Details(int id)
        {
            var candy = _candyRepository.GetCandyById(id);
            if(candy == null)
            {
                return NotFound();
            }
            return View(candy);
        }
    }
}

WebShop-Candy/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebShop_Candy.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebShop-Candy/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Mvc;
using WebShop_Candy.Models;
using WebShop_Candy.Service;
using WebShop_Candy.ViewModels;

namespace WebShop_Candy.Controllers
{
    public class ShoppingCartController : Controller
    {

        private readonly ICandyRepository _candyRepo;
        private readonly ShoppingCart _shoppinCart;

        public ShoppingCartController(ICandyRepository candyRepository, ShoppingCart shoppingCart)
        {
            _candyRepo = candyRepository;
            _shoppinCart = shoppingCart;
        }

        public IActionResult Index()
        {
            _shoppinCart.ShoppingCartItems = _shoppinCart.GetShoppingCartItems();
            var shoppingCartViewModel = new ShoppinCartViewModel
            {
                ShoppingCart = _shoppinCart,
                shoppingCartTotal = _shoppinCart.GetShoppingCartTotal()
            };


            return View(shoppingCartViewModel);
        }


        public IActionResult AddToShoppingCart(int candyid)
        {
            var selectedCandy = _candyRepo.GetAllCandy.FirstOrDefault(c => c.CandyId == candyid);

            if (selectedCandy != null)
            {
                _shoppinCart.AddToCart(selectedCandy, 1);
            }

            return RedirectToAction("Index");
        }


        public IActionResult RemoveFromShoppingCart(int candyid)
        {
            var selectedCandy = _candyRepo.GetAllCandy.FirstOrDefault(c => c.CandyId == candyid);
            if (selectedCandy != null)
            {
                _shoppinCart.RemoveFromCart(selectedCandy);
            }

            return RedirectToAction("Index");
        }


        public IActionResult ClearCart()
        {
            _shoppinCart.ClearCart();
            return RedirectToAction("Index");
        }
    }
}

WebShop-Candy/Views/Shared/_Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

WebShop-Candy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop_Candy</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>

    <link href="~/content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">

                            <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                            @await Component.InvokeAsync("ShoppingCartSummary")
                            <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                            @await Component.InvokeAsync("CategoryMenu")
                            <partial name="_LoginPartial" />

                        </ul>
                    </div>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img class="img-responsive" src="~/Images/candyshoplogo.png" />
                </p>
            </div>
            <div class=col-md-9>
                @RenderBody()
            </div>
        </div>

    </div>
    
   

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebShop-Candy/Views/Shared/_candyCard.cshtml
@model Candy



<div class="col-sm-4 col-lg-4 col-md-4">

    <div class="thumbnail">
        <img src="@Model.ImageThumpnailUrl" alt="image for candy" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3> 
                <a asp-controller="Candy" 
                asp-action="Details" 
                asp-route-id="@Model.CandyId">
                @Model.Name
                </a>
                </h3>
            <p>@Model.Descrption</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" 
                asp-controller="ShoppingCart" 
                asp-action="AddToShoppingCart"
                   asp-route-candyid="@Model.CandyId">Add To Cart

                </a>
            </p>
        </div>
    </div>

</div>